import { LiveModeConfig, LiveModeId } from '../types/liveRadar';

export const liveModes: LiveModeConfig[] = [
  {
    id: 'commerce',
    label: '커머스 레이더',
    shortLabel: '커머스',
    userGoalText: '상품을 판매하고 싶어요',
    description: '구매 질문, 가격 반응, 전환 신호, 망설임 댓글을 감지합니다.',
    recommendedFor: '쇼핑라이브, 공동구매, 상품 판매, 클래스 판매',
    categories: [
      'price_question',
      'purchase_intent',
      'delivery_question',
      'stock_question',
      'option_question',
      'comparison_question',
      'hesitation',
      'complaint',
      'link_request',
      'positive_reaction',
    ],
    metrics: ['구매 온도', '가격 질문 수', '구매 의도 댓글 수', '망설임 댓글 수', '불만 위험도', '전환 타이밍'],
    alertRules: [
      {
        id: 'commerce-price-repeat',
        label: '가격 질문 반복',
        conditionDescription: '가격, 할인, 혜택 문의가 2건 이상 감지',
        message: '가격 질문이 반복되고 있습니다.',
        suggestedLine: '가격 궁금해하시는 분들이 많네요. 지금 혜택과 구매 방법을 다시 한 번 정리해드릴게요.',
        priority: 'high',
      },
      {
        id: 'commerce-link-guide',
        label: '구매 방법 안내',
        conditionDescription: '구매 의도 또는 링크 요청 증가',
        message: '구매 의도 댓글이 늘고 있습니다.',
        suggestedLine: '구매 원하시는 분들은 고정 댓글의 링크에서 옵션을 선택하시면 됩니다.',
        priority: 'medium',
      },
      {
        id: 'commerce-hesitation',
        label: '망설임 해소',
        conditionDescription: '사이즈, 배송, 환불 등 불안 요소 감지',
        message: '망설임 댓글이 증가했습니다.',
        suggestedLine: '고민되는 포인트가 있을 수 있어요. 배송, 교환, 사이즈 기준을 짧게 다시 안내드릴게요.',
        priority: 'medium',
      },
    ],
    reportSections: ['구매 질문 요약', '망설임 요인', '전환 가능 구간', '상품 FAQ 후보', '다음 라이브 개선점'],
  },
  {
    id: 'education',
    label: '교육 레이더',
    shortLabel: '교육',
    userGoalText: '사람들이 이해했는지 보고 싶어요',
    description: '이해도, 반복 질문, 혼란 구간, 실습 오류를 감지합니다.',
    recommendedFor: '강의, 세미나, 튜토리얼, 온라인 클래스',
    categories: [
      'understood',
      'confusion',
      'repeated_question',
      'practice_error',
      'example_request',
      'material_request',
      'speed_complaint',
      'difficulty_reaction',
      'next_topic_request',
    ],
    metrics: ['이해도', '혼란도', '반복 질문 수', '실습 오류 수', 'Q&A 필요도', '설명 보완 필요도'],
    alertRules: [
      {
        id: 'education-explain-again',
        label: '설명 보완 필요',
        conditionDescription: '다시 설명, 어렵다, 예시 요청 증가',
        message: '어렵다/다시 설명해달라는 반응이 늘었습니다.',
        suggestedLine: '여기서 헷갈리실 수 있어요. 쉬운 예시로 다시 설명드리겠습니다.',
        priority: 'high',
      },
      {
        id: 'education-qa',
        label: 'Q&A 전환',
        conditionDescription: '반복 질문 2건 이상',
        message: '반복 질문이 많습니다.',
        suggestedLine: '여기서 잠깐 멈추고 질문을 먼저 정리해보겠습니다.',
        priority: 'medium',
      },
      {
        id: 'education-practice-error',
        label: '실습 오류 해결',
        conditionDescription: '오류, 안 됨, 막힘 반응 증가',
        message: '실습 오류 댓글이 증가했습니다.',
        suggestedLine: '화면을 잠깐 멈추고 오류가 나는 지점을 단계별로 같이 확인해볼게요.',
        priority: 'high',
      },
    ],
    reportSections: ['어려웠던 개념', '반복 질문 TOP', '실습 오류 패턴', '다음 강의 보완점', 'FAQ 초안'],
  },
  {
    id: 'fandom',
    label: '팬덤 레이더',
    shortLabel: '팬덤',
    userGoalText: '팬들과 분위기를 보고 싶어요',
    description: '분위기, 밈, 충성도, 반응 폭발, 클립 후보를 감지합니다.',
    recommendedFor: '스트리머, 크리에이터, 팬 소통 방송, 게임 방송',
    categories: [
      'laughter',
      'excitement',
      'meme_candidate',
      'fan_affection',
      'playful_teasing',
      'request',
      'nickname_mention',
      'clip_candidate',
      'mood_drop',
      'conflict',
    ],
    metrics: ['방송 텐션', '웃음 반응 수', '밈 후보 수', '클립 후보 구간', '팬 충성 반응', '분위기 위험도'],
    alertRules: [
      {
        id: 'fandom-meme',
        label: '밈 후보 발생',
        conditionDescription: '밈, 별명, 반복 가능한 표현 감지',
        message: '방금 표현에 팬들이 강하게 반응하고 있습니다.',
        suggestedLine: '방금 말 다들 좋아하시네요. 한 번만 더 해볼까요?',
        priority: 'medium',
      },
      {
        id: 'fandom-clip',
        label: '클립 후보',
        conditionDescription: '웃음과 클립 요청 동시 감지',
        message: '웃음 반응이 급증했습니다.',
        suggestedLine: '방금 장면 다들 좋아하시네요. 이건 오늘 클립 후보로 저장해두겠습니다.',
        priority: 'high',
      },
      {
        id: 'fandom-mood',
        label: '분위기 회복',
        conditionDescription: '분위기 하락 또는 충돌 감지',
        message: '분위기가 약간 가라앉고 있습니다.',
        suggestedLine: '여기서 여러분 의견도 들어볼게요. 지금 가장 보고 싶은 장면은 뭐예요?',
        priority: 'medium',
      },
    ],
    reportSections: ['오늘의 밈 후보', '팬들이 가장 좋아한 장면', '클립 후보', '분위기 하락 구간', '다음 방송 소재'],
  },
  {
    id: 'issue',
    label: '이슈 레이더',
    shortLabel: '이슈',
    userGoalText: '논점과 반응을 보고 싶어요',
    description: '논점 변화, 찬반 흐름, 팩트체크 필요 주장, 과열 신호를 중립적으로 정리합니다.',
    recommendedFor: '정치, 시사, 뉴스, 사회 이슈, 토론 라이브',
    categories: [
      'support_opinion',
      'opposition_opinion',
      'conditional_agreement',
      'evidence_request',
      'fact_check_needed',
      'new_issue',
      'topic_drift',
      'personal_attack',
      'emotional_escalation',
      'hate_or_violent_expression',
      'unverified_claim',
      'host_question',
      'next_topic_request',
    ],
    metrics: ['논점 집중도', '갈등 과열도', '팩트체크 필요 건수', '새 쟁점 수', '논점 이탈도', '질문 밀도'],
    alertRules: [
      {
        id: 'issue-attack',
        label: '사안 중심 전환',
        conditionDescription: '인물 비난, 감정 과열, 공격 표현 증가',
        message: '댓글이 인물 비난으로 흐르고 있습니다.',
        suggestedLine: '개인에 대한 표현보다는 정책과 사안 중심으로 다시 정리해보겠습니다.',
        priority: 'high',
      },
      {
        id: 'issue-factcheck',
        label: '팩트체크 요청',
        conditionDescription: '근거, 출처, 팩트체크 요청 반복',
        message: '팩트체크 요청이 반복되고 있습니다.',
        suggestedLine: '이 부분은 확인이 필요한 내용이라 단정하지 않고, 근거를 확인한 뒤 다시 정리하겠습니다.',
        priority: 'high',
      },
      {
        id: 'issue-new-topic',
        label: '새 쟁점 수용',
        conditionDescription: '새 논점 또는 주제 전환 요청 감지',
        message: '새로운 쟁점이 떠오르고 있습니다.',
        suggestedLine: '새로 나온 쟁점은 현재 주제와 연결되는 부분만 짧게 짚고 넘어가겠습니다.',
        priority: 'medium',
      },
    ],
    reportSections: ['주요 논점 TOP', '찬성/반대/조건부 의견 요약', '팩트체크 필요 주장', '갈등 과열 구간', '다음 방송 후속 주제'],
    safetyGuidelines: [
      '특정 정당, 후보, 진영에 유리한 조작 추천을 생성하지 않는다.',
      '특정 집단 비하나 공격을 유도하지 않는다.',
      '확인되지 않은 주장을 사실처럼 단정하지 않는다.',
      '댓글 작성자의 정치 성향을 개인 단위로 프로파일링하지 않는다.',
      '선거 관련 특정 후보 지지 또는 반대 행동을 유도하지 않는다.',
      '혐오 표현을 재미 요소로 증폭하지 않는다.',
    ],
  },
];

export const liveModeById = liveModes.reduce(
  (acc, mode) => ({ ...acc, [mode.id]: mode }),
  {} as Record<LiveModeId, LiveModeConfig>,
);
